BEGIN TRANSACTION;
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO "auth_permission" VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO "auth_permission" VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO "auth_permission" VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO "auth_permission" VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO "auth_permission" VALUES(5,3,'add_permission','Can add permission');
INSERT INTO "auth_permission" VALUES(6,3,'change_permission','Can change permission');
INSERT INTO "auth_permission" VALUES(7,3,'delete_permission','Can delete permission');
INSERT INTO "auth_permission" VALUES(8,3,'view_permission','Can view permission');
INSERT INTO "auth_permission" VALUES(9,2,'add_group','Can add group');
INSERT INTO "auth_permission" VALUES(10,2,'change_group','Can change group');
INSERT INTO "auth_permission" VALUES(11,2,'delete_group','Can delete group');
INSERT INTO "auth_permission" VALUES(12,2,'view_group','Can view group');
INSERT INTO "auth_permission" VALUES(13,4,'add_user','Can add user');
INSERT INTO "auth_permission" VALUES(14,4,'change_user','Can change user');
INSERT INTO "auth_permission" VALUES(15,4,'delete_user','Can delete user');
INSERT INTO "auth_permission" VALUES(16,4,'view_user','Can view user');
INSERT INTO "auth_permission" VALUES(17,5,'add_contenttype','Can add content type');
INSERT INTO "auth_permission" VALUES(18,5,'change_contenttype','Can change content type');
INSERT INTO "auth_permission" VALUES(19,5,'delete_contenttype','Can delete content type');
INSERT INTO "auth_permission" VALUES(20,5,'view_contenttype','Can view content type');
INSERT INTO "auth_permission" VALUES(21,6,'add_session','Can add session');
INSERT INTO "auth_permission" VALUES(22,6,'change_session','Can change session');
INSERT INTO "auth_permission" VALUES(23,6,'delete_session','Can delete session');
INSERT INTO "auth_permission" VALUES(24,6,'view_session','Can view session');
INSERT INTO "auth_permission" VALUES(25,16,'add_registrodiario','Can add Registro diario');
INSERT INTO "auth_permission" VALUES(26,16,'change_registrodiario','Can change Registro diario');
INSERT INTO "auth_permission" VALUES(27,16,'delete_registrodiario','Can delete Registro diario');
INSERT INTO "auth_permission" VALUES(28,16,'view_registrodiario','Can view Registro diario');
INSERT INTO "auth_permission" VALUES(29,15,'add_recomendacionemocion','Can add Relación recomendación-emoción');
INSERT INTO "auth_permission" VALUES(30,15,'change_recomendacionemocion','Can change Relación recomendación-emoción');
INSERT INTO "auth_permission" VALUES(31,15,'delete_recomendacionemocion','Can delete Relación recomendación-emoción');
INSERT INTO "auth_permission" VALUES(32,15,'view_recomendacionemocion','Can view Relación recomendación-emoción');
INSERT INTO "auth_permission" VALUES(33,11,'add_logro','Can add Logro');
INSERT INTO "auth_permission" VALUES(34,11,'change_logro','Can change Logro');
INSERT INTO "auth_permission" VALUES(35,11,'delete_logro','Can delete Logro');
INSERT INTO "auth_permission" VALUES(36,11,'view_logro','Can view Logro');
INSERT INTO "auth_permission" VALUES(37,10,'add_emocionregistrada','Can add Emoción registrada');
INSERT INTO "auth_permission" VALUES(38,10,'change_emocionregistrada','Can change Emoción registrada');
INSERT INTO "auth_permission" VALUES(39,10,'delete_emocionregistrada','Can delete Emoción registrada');
INSERT INTO "auth_permission" VALUES(40,10,'view_emocionregistrada','Can view Emoción registrada');
INSERT INTO "auth_permission" VALUES(41,12,'add_logrousuario','Can add Logro usuario');
INSERT INTO "auth_permission" VALUES(42,12,'change_logrousuario','Can change Logro usuario');
INSERT INTO "auth_permission" VALUES(43,12,'delete_logrousuario','Can delete Logro usuario');
INSERT INTO "auth_permission" VALUES(44,12,'view_logrousuario','Can view Logro usuario');
INSERT INTO "auth_permission" VALUES(45,13,'add_profile','Can add profile');
INSERT INTO "auth_permission" VALUES(46,13,'change_profile','Can change profile');
INSERT INTO "auth_permission" VALUES(47,13,'delete_profile','Can delete profile');
INSERT INTO "auth_permission" VALUES(48,13,'view_profile','Can view profile');
INSERT INTO "auth_permission" VALUES(49,9,'add_emocion','Can add Emocion');
INSERT INTO "auth_permission" VALUES(50,9,'change_emocion','Can change Emocion');
INSERT INTO "auth_permission" VALUES(51,9,'delete_emocion','Can delete Emocion');
INSERT INTO "auth_permission" VALUES(52,9,'view_emocion','Can view Emocion');
INSERT INTO "auth_permission" VALUES(53,14,'add_recomendacion','Can add recomendacion');
INSERT INTO "auth_permission" VALUES(54,14,'change_recomendacion','Can change recomendacion');
INSERT INTO "auth_permission" VALUES(55,14,'delete_recomendacion','Can delete recomendacion');
INSERT INTO "auth_permission" VALUES(56,14,'view_recomendacion','Can view recomendacion');
INSERT INTO "auth_permission" VALUES(57,7,'add_actividad','Can add actividad');
INSERT INTO "auth_permission" VALUES(58,7,'change_actividad','Can change actividad');
INSERT INTO "auth_permission" VALUES(59,7,'delete_actividad','Can delete actividad');
INSERT INTO "auth_permission" VALUES(60,7,'view_actividad','Can view actividad');
INSERT INTO "auth_permission" VALUES(61,8,'add_actividadrealizada','Can add Actividad realizada');
INSERT INTO "auth_permission" VALUES(62,8,'change_actividadrealizada','Can change Actividad realizada');
INSERT INTO "auth_permission" VALUES(63,8,'delete_actividadrealizada','Can delete Actividad realizada');
INSERT INTO "auth_permission" VALUES(64,8,'view_actividadrealizada','Can view Actividad realizada');
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
INSERT INTO "auth_user" VALUES(1,'pbkdf2_sha256$1200000$LxYrBGkOC0EFBOQchOmj8d$IDeDykFXosYAcJxzbq+qgNlv/gNIfrypngqCatWtpU0=','2026-04-23 22:19:08.228208',1,'carlos','','carlosmiguens861@gmail.com',1,1,'2026-03-15 11:25:36','');
INSERT INTO "auth_user" VALUES(2,'pbkdf2_sha256$1200000$wrXx9RCh6U23VvKbxO7W8I$sIciT6xto+jLS0zwU01Y+sd4jzBdObVlwM40A764c7o=',NULL,0,'jose@jose','','',0,1,'2026-03-20 20:55:42.096101','');
INSERT INTO "auth_user" VALUES(5,'pbkdf2_sha256$1200000$FrfXbGYMwHETlbOrwTV932$8oJaPB9USRDJ/kh6hMB9eVLKlda+NiQrCdNPpskM9h4=',NULL,0,'julia@julia.com','','julia@julia.com',0,1,'2026-03-21 14:16:19','');
INSERT INTO "auth_user" VALUES(7,'pbkdf2_sha256$1200000$Itb4US5MV5PdK4RrYyGr1O$02f47kdfyiJc6vpPUONyfRrp8+Y9IIwvH6lhqASfnJg=',NULL,0,'jhk@gimena.com','','jhk@gimena.com',0,1,'2026-03-21 14:19:49.407272','');
INSERT INTO "auth_user" VALUES(8,'pbkdf2_sha256$1200000$jyY0anzvmsvxao4MZnFkzu$ojPTkXKQAvzAxY980gep2lM3YxXansFJczhvQKx4+aI=',NULL,0,'pepe@pepe.com','','pepe@pepe.com',0,1,'2026-03-23 23:54:08.724495','');
INSERT INTO "auth_user" VALUES(9,'pbkdf2_sha256$1200000$xa5tVgFbjoXcqvBxnDe1dn$DFs7AptLN9cL0l8EabyxzYaM28CLAq5168zUt0o6xbA=',NULL,0,'marcos@marcos.com','','marcos@marcos.com',0,1,'2026-03-24 00:02:06.296608','');
CREATE TABLE "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "backFeelifyme_actividad" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL UNIQUE);
INSERT INTO "backFeelifyme_actividad" VALUES(1,'caminar');
INSERT INTO "backFeelifyme_actividad" VALUES(2,'cocinar');
INSERT INTO "backFeelifyme_actividad" VALUES(3,'correr');
INSERT INTO "backFeelifyme_actividad" VALUES(4,'deporte');
INSERT INTO "backFeelifyme_actividad" VALUES(5,'socializar');
INSERT INTO "backFeelifyme_actividad" VALUES(6,'tocar_instrumento');
INSERT INTO "backFeelifyme_actividad" VALUES(7,'leer');
INSERT INTO "backFeelifyme_actividad" VALUES(8,'meditar');
CREATE TABLE "backFeelifyme_actividadrealizada" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "actividad_id" bigint NOT NULL REFERENCES "backFeelifyme_actividad" ("id") DEFERRABLE INITIALLY DEFERRED, "registro_id" bigint NOT NULL REFERENCES "backFeelifyme_registrodiario" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(1,1,1);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(7,8,4);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(8,6,4);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(9,3,5);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(10,6,5);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(11,3,6);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(12,6,6);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(13,3,7);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(14,6,7);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(15,5,8);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(16,7,8);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(17,1,10);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(18,5,10);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(19,4,10);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(20,2,11);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(21,7,11);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(22,3,15);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(23,7,15);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(24,2,16);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(25,7,16);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(26,1,16);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(27,8,17);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(28,7,17);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(29,2,17);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(30,3,18);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(31,8,18);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(32,8,19);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(33,6,19);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(34,1,20);
INSERT INTO "backFeelifyme_actividadrealizada" VALUES(35,4,20);
CREATE TABLE "backFeelifyme_emocion" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL UNIQUE, "nivel" varchar(1) NOT NULL, "padre_id" bigint NULL REFERENCES "backFeelifyme_emocion" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "backFeelifyme_emocion" VALUES(1,'Felicidad','1',NULL);
INSERT INTO "backFeelifyme_emocion" VALUES(2,'Orgulloso','2',1);
INSERT INTO "backFeelifyme_emocion" VALUES(3,'Importante','3',2);
INSERT INTO "backFeelifyme_emocion" VALUES(4,'Confiado','3',2);
INSERT INTO "backFeelifyme_emocion" VALUES(5,'Aceptado','2',1);
INSERT INTO "backFeelifyme_emocion" VALUES(6,'Respetado','3',5);
INSERT INTO "backFeelifyme_emocion" VALUES(7,'Realizado','3',5);
INSERT INTO "backFeelifyme_emocion" VALUES(8,'Poderoso','2',1);
INSERT INTO "backFeelifyme_emocion" VALUES(9,'Provocativo','3',8);
INSERT INTO "backFeelifyme_emocion" VALUES(10,'Valiente','3',8);
INSERT INTO "backFeelifyme_emocion" VALUES(11,'Pacífico','2',1);
INSERT INTO "backFeelifyme_emocion" VALUES(12,'Amoroso','3',11);
INSERT INTO "backFeelifyme_emocion" VALUES(13,'Esperanzado','3',11);
INSERT INTO "backFeelifyme_emocion" VALUES(14,'Íntimo','2',1);
INSERT INTO "backFeelifyme_emocion" VALUES(15,'Sensible','3',14);
INSERT INTO "backFeelifyme_emocion" VALUES(16,'Juguetón','3',14);
INSERT INTO "backFeelifyme_emocion" VALUES(17,'Optimista','2',1);
INSERT INTO "backFeelifyme_emocion" VALUES(18,'Receptivo','3',17);
INSERT INTO "backFeelifyme_emocion" VALUES(19,'Inspirado','3',17);
INSERT INTO "backFeelifyme_emocion" VALUES(20,'Tristeza','1',NULL);
INSERT INTO "backFeelifyme_emocion" VALUES(21,'Aburrido','2',20);
INSERT INTO "backFeelifyme_emocion" VALUES(22,'Indiferente','3',21);
INSERT INTO "backFeelifyme_emocion" VALUES(23,'Apático','3',21);
INSERT INTO "backFeelifyme_emocion" VALUES(24,'Solitario','2',20);
INSERT INTO "backFeelifyme_emocion" VALUES(25,'Apartado','3',24);
INSERT INTO "backFeelifyme_emocion" VALUES(26,'Abandonado','3',24);
INSERT INTO "backFeelifyme_emocion" VALUES(27,'Deprimido','2',20);
INSERT INTO "backFeelifyme_emocion" VALUES(28,'Vacío','3',27);
INSERT INTO "backFeelifyme_emocion" VALUES(29,'Inferior','3',27);
INSERT INTO "backFeelifyme_emocion" VALUES(30,'Desesperado','2',20);
INSERT INTO "backFeelifyme_emocion" VALUES(31,'Vulnerable','3',30);
INSERT INTO "backFeelifyme_emocion" VALUES(32,'Impotente','3',30);
INSERT INTO "backFeelifyme_emocion" VALUES(33,'Abandonado (Tristeza)','2',20);
INSERT INTO "backFeelifyme_emocion" VALUES(34,'Discriminado','3',33);
INSERT INTO "backFeelifyme_emocion" VALUES(35,'Ignorado','3',33);
INSERT INTO "backFeelifyme_emocion" VALUES(36,'Ansioso','2',20);
INSERT INTO "backFeelifyme_emocion" VALUES(37,'Abrumado','3',36);
INSERT INTO "backFeelifyme_emocion" VALUES(38,'Anhelante','3',36);
INSERT INTO "backFeelifyme_emocion" VALUES(39,'Disgusto','1',NULL);
INSERT INTO "backFeelifyme_emocion" VALUES(40,'Culpable','2',39);
INSERT INTO "backFeelifyme_emocion" VALUES(41,'Avergonzado','3',40);
INSERT INTO "backFeelifyme_emocion" VALUES(42,'Atormentado','3',40);
INSERT INTO "backFeelifyme_emocion" VALUES(43,'Evasivo','2',39);
INSERT INTO "backFeelifyme_emocion" VALUES(44,'Indeciso','3',43);
INSERT INTO "backFeelifyme_emocion" VALUES(45,'Aversivo','3',43);
INSERT INTO "backFeelifyme_emocion" VALUES(46,'Terrible','2',39);
INSERT INTO "backFeelifyme_emocion" VALUES(47,'Detestable','3',46);
INSERT INTO "backFeelifyme_emocion" VALUES(48,'Repulsivo','3',46);
INSERT INTO "backFeelifyme_emocion" VALUES(49,'Decepcionado','2',39);
INSERT INTO "backFeelifyme_emocion" VALUES(50,'Rebelado','3',49);
INSERT INTO "backFeelifyme_emocion" VALUES(51,'Repugnante','3',49);
INSERT INTO "backFeelifyme_emocion" VALUES(52,'Desaprobado','2',39);
INSERT INTO "backFeelifyme_emocion" VALUES(53,'Aborrecido','3',52);
INSERT INTO "backFeelifyme_emocion" VALUES(54,'Sentencioso','3',52);
INSERT INTO "backFeelifyme_emocion" VALUES(55,'Crítico','2',39);
INSERT INTO "backFeelifyme_emocion" VALUES(56,'Escéptico','3',55);
INSERT INTO "backFeelifyme_emocion" VALUES(57,'Sarcástico','3',55);
INSERT INTO "backFeelifyme_emocion" VALUES(58,'Ira','1',NULL);
INSERT INTO "backFeelifyme_emocion" VALUES(59,'Distante','2',58);
INSERT INTO "backFeelifyme_emocion" VALUES(60,'Sospechoso','3',59);
INSERT INTO "backFeelifyme_emocion" VALUES(61,'Retraído','3',59);
INSERT INTO "backFeelifyme_emocion" VALUES(62,'Frustrado','2',58);
INSERT INTO "backFeelifyme_emocion" VALUES(63,'Irritado','3',62);
INSERT INTO "backFeelifyme_emocion" VALUES(64,'Enfadado','3',62);
INSERT INTO "backFeelifyme_emocion" VALUES(65,'Agresivo','2',58);
INSERT INTO "backFeelifyme_emocion" VALUES(66,'Hostil','3',65);
INSERT INTO "backFeelifyme_emocion" VALUES(67,'Provocado','3',65);
INSERT INTO "backFeelifyme_emocion" VALUES(68,'Desquiciado','2',58);
INSERT INTO "backFeelifyme_emocion" VALUES(69,'Rabioso','3',68);
INSERT INTO "backFeelifyme_emocion" VALUES(70,'Enfurecido','3',68);
INSERT INTO "backFeelifyme_emocion" VALUES(71,'Odioso','2',58);
INSERT INTO "backFeelifyme_emocion" VALUES(72,'Violado','3',71);
INSERT INTO "backFeelifyme_emocion" VALUES(73,'Resentido','3',71);
INSERT INTO "backFeelifyme_emocion" VALUES(74,'Amenazado','2',58);
INSERT INTO "backFeelifyme_emocion" VALUES(75,'Celoso','3',74);
INSERT INTO "backFeelifyme_emocion" VALUES(76,'Inseguro','3',74);
INSERT INTO "backFeelifyme_emocion" VALUES(77,'Miedo','1',NULL);
INSERT INTO "backFeelifyme_emocion" VALUES(78,'Asustado','2',77);
INSERT INTO "backFeelifyme_emocion" VALUES(79,'Devastado','3',78);
INSERT INTO "backFeelifyme_emocion" VALUES(80,'Apenado','3',78);
INSERT INTO "backFeelifyme_emocion" VALUES(81,'Inseguro (Miedo)','2',77);
INSERT INTO "backFeelifyme_emocion" VALUES(82,'Ridiculizado','3',81);
INSERT INTO "backFeelifyme_emocion" VALUES(83,'Irrespetado','3',81);
INSERT INTO "backFeelifyme_emocion" VALUES(84,'Sumiso','2',77);
INSERT INTO "backFeelifyme_emocion" VALUES(85,'Perturbado','3',84);
INSERT INTO "backFeelifyme_emocion" VALUES(86,'Inadecuado','3',84);
INSERT INTO "backFeelifyme_emocion" VALUES(87,'Rechazado','2',77);
INSERT INTO "backFeelifyme_emocion" VALUES(88,'Insignificante','3',87);
INSERT INTO "backFeelifyme_emocion" VALUES(89,'Indignado','3',87);
INSERT INTO "backFeelifyme_emocion" VALUES(90,'Humillado','2',77);
INSERT INTO "backFeelifyme_emocion" VALUES(91,'Inferior (Humillado)','3',90);
INSERT INTO "backFeelifyme_emocion" VALUES(92,'Pobre','3',90);
INSERT INTO "backFeelifyme_emocion" VALUES(93,'Herido','2',77);
INSERT INTO "backFeelifyme_emocion" VALUES(94,'Espantado','3',93);
INSERT INTO "backFeelifyme_emocion" VALUES(95,'Aterrado','3',93);
INSERT INTO "backFeelifyme_emocion" VALUES(96,'Sorpresa','1',NULL);
INSERT INTO "backFeelifyme_emocion" VALUES(97,'Asombrado','2',96);
INSERT INTO "backFeelifyme_emocion" VALUES(98,'Entretenido','3',114);
INSERT INTO "backFeelifyme_emocion" VALUES(99,'Curioso','3',114);
INSERT INTO "backFeelifyme_emocion" VALUES(100,'Confundido','2',96);
INSERT INTO "backFeelifyme_emocion" VALUES(101,'Impresionado','3',100);
INSERT INTO "backFeelifyme_emocion" VALUES(102,'Consternado','3',100);
INSERT INTO "backFeelifyme_emocion" VALUES(103,'Sorprendido','2',96);
INSERT INTO "backFeelifyme_emocion" VALUES(104,'Desilusionado','3',103);
INSERT INTO "backFeelifyme_emocion" VALUES(105,'Perplejo','3',103);
INSERT INTO "backFeelifyme_emocion" VALUES(106,'Efusivo','2',96);
INSERT INTO "backFeelifyme_emocion" VALUES(107,'Atónito','3',97);
INSERT INTO "backFeelifyme_emocion" VALUES(108,'Pasmado','3',97);
INSERT INTO "backFeelifyme_emocion" VALUES(109,'Jubiloso','2',96);
INSERT INTO "backFeelifyme_emocion" VALUES(110,'Inquieto','3',106);
INSERT INTO "backFeelifyme_emocion" VALUES(111,'Enérgico','3',106);
INSERT INTO "backFeelifyme_emocion" VALUES(112,'Liberado','3',109);
INSERT INTO "backFeelifyme_emocion" VALUES(113,'Eufórico','3',109);
INSERT INTO "backFeelifyme_emocion" VALUES(114,'Interesado','2',96);
CREATE TABLE "backFeelifyme_emocionregistrada" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "emocion_id" bigint NOT NULL REFERENCES "backFeelifyme_emocion" ("id") DEFERRABLE INITIALLY DEFERRED, "registro_id" bigint NOT NULL REFERENCES "backFeelifyme_registrodiario" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(1,1,1);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(2,2,1);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(3,3,4);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(4,87,4);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(5,96,5);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(6,14,5);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(7,3,5);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(8,96,6);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(9,14,6);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(10,3,6);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(11,96,7);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(12,14,7);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(13,3,7);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(14,27,8);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(15,65,8);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(16,77,8);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(17,9,10);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(18,87,10);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(19,20,10);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(20,68,10);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(21,49,11);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(22,107,11);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(23,85,13);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(24,68,15);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(25,85,15);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(26,96,16);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(27,31,16);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(28,11,16);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(29,104,17);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(30,14,17);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(31,46,17);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(32,58,17);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(33,3,18);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(34,106,18);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(35,39,18);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(36,10,19);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(37,103,19);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(38,30,19);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(39,3,20);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(40,93,20);
INSERT INTO "backFeelifyme_emocionregistrada" VALUES(41,59,20);
CREATE TABLE "backFeelifyme_logro" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL UNIQUE, "descripcion" text NOT NULL, "tipo" varchar(50) NULL);
CREATE TABLE "backFeelifyme_logrousuario" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "fecha_obtenido" datetime NOT NULL, "logro_id" bigint NOT NULL REFERENCES "backFeelifyme_logro" ("id") DEFERRABLE INITIALLY DEFERRED, "usuario_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "backFeelifyme_profile" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nombre" varchar(100) NOT NULL, "apellido1" varchar(100) NOT NULL, "apellido2" varchar(100) NULL, "dni" varchar(100) NULL UNIQUE, "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "backFeelifyme_profile" VALUES(3,'julia','miriera','gonzalez',NULL,5);
INSERT INTO "backFeelifyme_profile" VALUES(5,'hjk','miriera','gonzalez',NULL,7);
INSERT INTO "backFeelifyme_profile" VALUES(6,'Pepe','Lisa','Lisa',NULL,8);
INSERT INTO "backFeelifyme_profile" VALUES(7,'Marcos','Perez','Perez',NULL,9);
CREATE TABLE "backFeelifyme_recomendacion" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "titulo" varchar(100) NOT NULL UNIQUE, "descripcion" text NOT NULL);
CREATE TABLE "backFeelifyme_recomendacionemocion" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "emocion_id" bigint NOT NULL REFERENCES "backFeelifyme_emocion" ("id") DEFERRABLE INITIALLY DEFERRED, "recomendacion_id" bigint NOT NULL REFERENCES "backFeelifyme_recomendacion" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "backFeelifyme_registrodiario" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "fecha" date NOT NULL, "notas" text NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "usuario_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "backFeelifyme_registrodiario" VALUES(1,'2026-04-14','Hoy ha sido un buen día, estuve avanzando un montón con el TFC y luego descansé.','2026-04-14 18:45:37.689102','2026-04-14 18:45:37.689118',2);
INSERT INTO "backFeelifyme_registrodiario" VALUES(4,'2026-04-14','lllll','2026-04-14 21:12:53.442937','2026-04-14 21:12:53.442951',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(5,'2026-04-16','se hizo','2026-04-16 18:24:32.466633','2026-04-16 18:24:32.466724',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(6,'2026-04-16','se hizo','2026-04-16 18:24:38.928856','2026-04-16 18:24:38.928877',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(7,'2026-04-16','se hizo','2026-04-16 18:24:49.988019','2026-04-16 18:24:49.988053',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(8,'2026-04-16','mal','2026-04-16 22:07:00.349556','2026-04-16 22:07:00.349598',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(9,'2026-04-16','','2026-04-16 22:07:06.121666','2026-04-16 22:07:06.121692',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(10,'2026-04-21','Nota actualizada','2026-04-21 07:58:52.868907','2026-04-21 08:07:02.319839',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(11,'2026-04-21','guachi','2026-04-21 19:17:01.130901','2026-04-21 19:17:01.130953',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(12,'2026-04-21','','2026-04-21 19:17:03.940346','2026-04-21 19:17:03.940364',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(13,'2026-04-21','','2026-04-21 19:17:28.323074','2026-04-21 19:17:28.323089',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(14,'2026-04-21','','2026-04-21 19:17:33.009762','2026-04-21 19:17:33.009782',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(15,'2026-04-24','bien yuju','2026-04-24 21:59:34.276810','2026-04-24 21:59:34.276919',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(16,'2026-05-14','casa','2026-05-14 12:29:49.471257','2026-05-14 12:29:49.471277',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(17,'2026-05-19','brrr','2026-05-19 08:37:33.482111','2026-05-19 08:37:33.482346',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(18,'2026-05-28','trs','2026-05-28 21:08:41.562377','2026-05-28 21:08:41.562781',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(19,'2026-05-29','bv','2026-05-29 14:28:00.972267','2026-05-29 14:28:00.972282',5);
INSERT INTO "backFeelifyme_registrodiario" VALUES(20,'2026-05-29','gbdf','2026-05-29 19:12:55.691896','2026-05-29 19:12:55.692121',5);
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
INSERT INTO "django_admin_log" VALUES(1,'2','jose@jose',1,'[{"added": {}}]',4,1,'2026-03-20 20:55:42.716084');
INSERT INTO "django_admin_log" VALUES(2,'4','maria@maria.com',3,'',4,1,'2026-03-21 14:15:23.212018');
INSERT INTO "django_admin_log" VALUES(3,'3','pedro@pedro.com',3,'',4,1,'2026-03-21 14:15:30.479006');
INSERT INTO "django_admin_log" VALUES(4,'1','carlos',2,'[{"changed": {"fields": ["password"]}}]',4,1,'2026-04-14 20:55:06.224144');
INSERT INTO "django_admin_log" VALUES(5,'1','carlos',2,'[]',4,1,'2026-04-14 20:56:10.575315');
INSERT INTO "django_admin_log" VALUES(6,'1','carlos',2,'[{"changed": {"fields": ["password"]}}]',4,1,'2026-04-14 20:57:34.555472');
INSERT INTO "django_admin_log" VALUES(7,'1','carlos',2,'[{"changed": {"fields": ["password"]}}]',4,1,'2026-04-14 20:58:20.034605');
INSERT INTO "django_admin_log" VALUES(8,'1','carlos',2,'[]',4,1,'2026-04-14 20:58:25.249380');
INSERT INTO "django_admin_log" VALUES(9,'6','gimena@gimena.com',2,'[{"changed": {"fields": ["password"]}}]',4,1,'2026-04-14 20:59:08.823300');
INSERT INTO "django_admin_log" VALUES(10,'6','gimena@gimena.com',2,'[]',4,1,'2026-04-14 20:59:25.065063');
INSERT INTO "django_admin_log" VALUES(11,'5','julia@julia.com',2,'[{"changed": {"fields": ["password"]}}]',4,1,'2026-04-14 21:12:01.554487');
INSERT INTO "django_admin_log" VALUES(12,'5','julia@julia.com',2,'[]',4,1,'2026-04-14 21:12:06.348875');
INSERT INTO "django_admin_log" VALUES(13,'5','julia@julia.com',2,'[{"changed": {"fields": ["password"]}}]',4,1,'2026-04-21 07:51:57.738271');
INSERT INTO "django_admin_log" VALUES(14,'5','julia@julia.com',2,'[]',4,1,'2026-04-21 07:52:01.095122');
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO "django_content_type" VALUES(1,'admin','logentry');
INSERT INTO "django_content_type" VALUES(2,'auth','group');
INSERT INTO "django_content_type" VALUES(3,'auth','permission');
INSERT INTO "django_content_type" VALUES(4,'auth','user');
INSERT INTO "django_content_type" VALUES(5,'contenttypes','contenttype');
INSERT INTO "django_content_type" VALUES(6,'sessions','session');
INSERT INTO "django_content_type" VALUES(7,'backFeelifyme','actividad');
INSERT INTO "django_content_type" VALUES(8,'backFeelifyme','actividadrealizada');
INSERT INTO "django_content_type" VALUES(9,'backFeelifyme','emocion');
INSERT INTO "django_content_type" VALUES(10,'backFeelifyme','emocionregistrada');
INSERT INTO "django_content_type" VALUES(11,'backFeelifyme','logro');
INSERT INTO "django_content_type" VALUES(12,'backFeelifyme','logrousuario');
INSERT INTO "django_content_type" VALUES(13,'backFeelifyme','profile');
INSERT INTO "django_content_type" VALUES(14,'backFeelifyme','recomendacion');
INSERT INTO "django_content_type" VALUES(15,'backFeelifyme','recomendacionemocion');
INSERT INTO "django_content_type" VALUES(16,'backFeelifyme','registrodiario');
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO "django_migrations" VALUES(1,'contenttypes','0001_initial','2026-03-15 11:09:38.733884');
INSERT INTO "django_migrations" VALUES(2,'auth','0001_initial','2026-03-15 11:09:38.749635');
INSERT INTO "django_migrations" VALUES(3,'admin','0001_initial','2026-03-15 11:09:38.759277');
INSERT INTO "django_migrations" VALUES(4,'admin','0002_logentry_remove_auto_add','2026-03-15 11:09:38.769175');
INSERT INTO "django_migrations" VALUES(5,'admin','0003_logentry_add_action_flag_choices','2026-03-15 11:09:38.775095');
INSERT INTO "django_migrations" VALUES(6,'contenttypes','0002_remove_content_type_name','2026-03-15 11:09:38.789731');
INSERT INTO "django_migrations" VALUES(7,'auth','0002_alter_permission_name_max_length','2026-03-15 11:09:38.798552');
INSERT INTO "django_migrations" VALUES(8,'auth','0003_alter_user_email_max_length','2026-03-15 11:09:38.807157');
INSERT INTO "django_migrations" VALUES(9,'auth','0004_alter_user_username_opts','2026-03-15 11:09:38.813027');
INSERT INTO "django_migrations" VALUES(10,'auth','0005_alter_user_last_login_null','2026-03-15 11:09:38.822306');
INSERT INTO "django_migrations" VALUES(11,'auth','0006_require_contenttypes_0002','2026-03-15 11:09:38.825305');
INSERT INTO "django_migrations" VALUES(12,'auth','0007_alter_validators_add_error_messages','2026-03-15 11:09:38.831522');
INSERT INTO "django_migrations" VALUES(13,'auth','0008_alter_user_username_max_length','2026-03-15 11:09:38.841807');
INSERT INTO "django_migrations" VALUES(14,'auth','0009_alter_user_last_name_max_length','2026-03-15 11:09:38.849994');
INSERT INTO "django_migrations" VALUES(15,'auth','0010_alter_group_name_max_length','2026-03-15 11:09:38.858770');
INSERT INTO "django_migrations" VALUES(16,'auth','0011_update_proxy_permissions','2026-03-15 11:09:38.865318');
INSERT INTO "django_migrations" VALUES(17,'auth','0012_alter_user_first_name_max_length','2026-03-15 11:09:38.874656');
INSERT INTO "django_migrations" VALUES(18,'sessions','0001_initial','2026-03-15 11:09:38.880120');
INSERT INTO "django_migrations" VALUES(19,'backFeelifyme','0001_initial','2026-03-15 11:23:06.627076');
INSERT INTO "django_migrations" VALUES(20,'backFeelifyme','0002_alter_emocionregistrada_unique_together','2026-04-13 22:47:37.946743');
INSERT INTO "django_migrations" VALUES(21,'backFeelifyme','0003_alter_registrodiario_unique_together_and_more','2026-04-13 23:17:06.168202');
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
INSERT INTO "django_session" VALUES('yb5jdroktjc1wd4de5dvqrsstgwzeg8d','.eJxVjEEOwiAQRe_C2pBCYei4dO8ZyMCAVA0kpV0Z765NutDtf-_9l_C0rcVvPS1-ZnEWSpx-t0DxkeoO-E711mRsdV3mIHdFHrTLa-P0vBzu30GhXr51UiMkyJCNihNaRAQmdI4DRBqBp0EFBZq1Q201D2xcRsfG6Iw6WRbvD9UdN2o:1w1jcw:rxEcfk1oxMxEbSoB0FSzkiigFKfaDjjlxmHr1uY_dpE','2026-03-29 11:27:22.345033');
INSERT INTO "django_session" VALUES('6tp85za1de4kgntiap1a7bhyx3izpsv1','.eJxVjEEOwiAQRe_C2pChkAAu3XsGMjAzUjWQlHZlvLs26UK3_733Xyrhtta0DV7STOqsjDr9bhnLg9sO6I7t1nXpbV3mrHdFH3Toayd-Xg7376DiqN86OhKQwISUfShCDCY6w07KZNmAL05yjtHDBBjBW8AQjPVAKORcVu8PCC84Ww:1wF5tl:6xVk1-UgfmCWR4gQV-9cA9ouChZyJIDglKOmBfQqbZY','2026-05-05 07:51:57.754015');
INSERT INTO "django_session" VALUES('pojhmyzultifj3p9c6susnqhxgop2s3l','.eJxVjEEOwiAQRe_C2hCYUqAu3XsGMsOAVA0kpV0Z765NutDtf-_9lwi4rSVsPS1hZnEWWpx-N8L4SHUHfMd6azK2ui4zyV2RB-3y2jg9L4f7d1Cwl2_tDXAkpEEb1CYC0qRGq5SxA2OKZgI7elDorALnMkftU_YegPNgLHnx_gDV3Tdj:1wG2O4:BeX7AeJtKOK7VipXqn7oCUQtKRw2XoLRVN6Jm0ak3aI','2026-05-07 22:19:08.231525');
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "backFeelifyme_emocion_padre_id_e425fdce" ON "backFeelifyme_emocion" ("padre_id");
CREATE UNIQUE INDEX "backFeelifyme_recomendacionemocion_recomendacion_id_emocion_id_6886456f_uniq" ON "backFeelifyme_recomendacionemocion" ("recomendacion_id", "emocion_id");
CREATE INDEX "backFeelifyme_recomendacionemocion_emocion_id_e0327195" ON "backFeelifyme_recomendacionemocion" ("emocion_id");
CREATE INDEX "backFeelifyme_recomendacionemocion_recomendacion_id_3b576872" ON "backFeelifyme_recomendacionemocion" ("recomendacion_id");
CREATE INDEX "backFeelifyme_registrodiario_usuario_id_e3ec353a" ON "backFeelifyme_registrodiario" ("usuario_id");
CREATE UNIQUE INDEX "backFeelifyme_logrousuario_usuario_id_logro_id_f1c7a2eb_uniq" ON "backFeelifyme_logrousuario" ("usuario_id", "logro_id");
CREATE INDEX "backFeelifyme_logrousuario_logro_id_cc9d6803" ON "backFeelifyme_logrousuario" ("logro_id");
CREATE INDEX "backFeelifyme_logrousuario_usuario_id_dd40b37a" ON "backFeelifyme_logrousuario" ("usuario_id");
CREATE INDEX "backFeelifyme_emocionregistrada_emocion_id_5d67c618" ON "backFeelifyme_emocionregistrada" ("emocion_id");
CREATE INDEX "backFeelifyme_emocionregistrada_registro_id_530e8db2" ON "backFeelifyme_emocionregistrada" ("registro_id");
CREATE UNIQUE INDEX "backFeelifyme_actividadrealizada_registro_id_actividad_id_757a3ab2_uniq" ON "backFeelifyme_actividadrealizada" ("registro_id", "actividad_id");
CREATE INDEX "backFeelifyme_actividadrealizada_actividad_id_ad08fb96" ON "backFeelifyme_actividadrealizada" ("actividad_id");
CREATE INDEX "backFeelifyme_actividadrealizada_registro_id_6177dc0b" ON "backFeelifyme_actividadrealizada" ("registro_id");
CREATE UNIQUE INDEX "backFeelifyme_emocionregistrada_registro_id_emocion_id_0995d1aa_uniq" ON "backFeelifyme_emocionregistrada" ("registro_id", "emocion_id");
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('django_migrations',21);
INSERT INTO "sqlite_sequence" VALUES('django_admin_log',14);
INSERT INTO "sqlite_sequence" VALUES('django_content_type',16);
INSERT INTO "sqlite_sequence" VALUES('auth_permission',64);
INSERT INTO "sqlite_sequence" VALUES('auth_group',0);
INSERT INTO "sqlite_sequence" VALUES('auth_user',9);
INSERT INTO "sqlite_sequence" VALUES('backFeelifyme_recomendacion',0);
INSERT INTO "sqlite_sequence" VALUES('backFeelifyme_profile',7);
INSERT INTO "sqlite_sequence" VALUES('backFeelifyme_emocion',114);
INSERT INTO "sqlite_sequence" VALUES('backFeelifyme_actividad',8);
INSERT INTO "sqlite_sequence" VALUES('backFeelifyme_registrodiario',20);
INSERT INTO "sqlite_sequence" VALUES('backFeelifyme_emocionregistrada',41);
INSERT INTO "sqlite_sequence" VALUES('backFeelifyme_actividadrealizada',35);
COMMIT;
