# Generated by Django 6.0.3 on 2026-07-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backFeelifyme', '0003_alter_registrodiario_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='logro',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logro',
            name='dificultad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logro',
            name='es_secreto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logro',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logro',
            name='requisito',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
