# Generated by Django 6.0.3 on 2026-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backFeelifyme', '0004_logro_activo_logro_categoria_logro_dificultad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'ordering': ['categoria', 'nombre']},
        ),
        migrations.AddField(
            model_name='actividad',
            name='categoria',
            field=models.CharField(choices=[('fisica', 'Física'), ('bienestar', 'Bienestar'), ('creativa', 'Creativa'), ('digital', 'Digital'), ('productiva', 'Productiva'), ('social', 'Social'), ('cotidiana', 'Cotidiana')], default='cotidiana', max_length=20),
        ),
    ]
